<a href="https://colab.research.google.com/github/colinkelleher/5-in-a-row-game/blob/master/CS6501_Lab_0_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div>
<img src="https://drive.google.com/uc?export=view&id=1vK33e_EqaHgBHcbRV_m38hx6IkG0blK_" width="350"/>
</div> 

#**Artificial Intelligence - MSc**
CS6501 - MACHINE LEARNING AND APPLICATIONS 

###Instructor: Enrique Naredo
###CS6501_Lab-0.8

# Numpy


This part focuses on Numpy, see <a href="https://numpy.org/doc/stable/user/quickstart.html">numpy quickstart tutorial</a>, which I encourage you to reference throughout the course.


Some problems about numpy



# Problem 11
Normalize a 5x5 random matrix

Solution:
>Z = np.random.random((5,5))
>
>Z = (Z - np.mean (Z)) / (np.std (Z))
>
>print(Z)


# Problem 12

Multiply a 5x3 matrix by a 3x2 matrix (matrix product).

Hint

    It is straightforward if you use np.matmul().

In [3]:
import numpy as np
X = np.random.random((5,3))
Y = np.random.random((3,2))
Z = np.dot(X,Y)
print("5x3 Matrix =>", X)
print("3x2 Matrix =>", Y)
print("5x3 Matrix multiply by 3x2 Matrix  =>", Z)

5x3 Matrix => [[0.56362191 0.44590795 0.32781921]
 [0.15980656 0.20728355 0.2082361 ]
 [0.6294724  0.41932418 0.72112373]
 [0.99848753 0.49113227 0.66391613]
 [0.81827568 0.71580828 0.00411935]]
3x2 Matrix => [[0.51131503 0.25240602]
 [0.55550905 0.08111732]
 [0.54664481 0.82811436]]
5x3 Matrix multiply by 3x2 Matrix  => [[0.71509493 0.44990422]
 [0.31069057 0.22959373]
 [0.94899563 0.79007   ]
 [1.14629641 0.84166208]
 [0.81828645 0.26801345]]


# Problem 13
Given a 1D array, negate in place all elements which are between 3 and 8.

In [6]:
Z = np.arange(10)

Z[3:9] = np.multiply(Z[3:9],-1)

print(Z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


# Problem 14
How to find common values between two arrays?


In [7]:
X = [1,2,3,4,5,6,7,8,9]
Y = [9,10,11,12]
Z = np.intersect1d(X,Y)
print(Z)

[9]


# Problem 15
How to find the most frequent value in an array? (Use `Z = np.random.randint(0,10,50)` to generate the array)

In [10]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[9 6 5 2 3 2 2 7 0 6 1 0 0 1 5 1 4 3 3 3 5 0 4 4 0 8 8 3 1 9 6 9 9 8 1 7 4
 5 3 0 5 9 2 3 9 4 2 3 6 5]
3
